# Generated by Django 2.1.7 on 2021-08-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('В доставке', 'В доставке'), ('Доставлен', 'Доставлен')], max_length=200, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('На складе', 'На складе'), ('Вне склада', 'Вне склада')], max_length=200, null=True, verbose_name='Категория'),
        ),
    ]
